// Generated by scripts/scan.mjs — do not edit by hand.
// Multi-marketplace catalog. Each entry: { marketplace:{name,addSource,description}, plugins:[...], generatedAt, mode }
window.PLUGIN_CATALOG = {
  "marketplaces": [
    {
      "marketplace": {
        "name": "seibtribemarket",
        "addSource": "geseib/seibtribemarket",
        "description": "Seib Tribe Market — reusable Claude Code skills."
      },
      "plugins": [
        {
          "name": "dynamodb-single-table",
          "description": "Designs DynamoDB tables using single table design with generic keys, co-located entities, and GSI overloading.",
          "version": "1.0.0",
          "author": "myskills",
          "category": "skill",
          "tags": [
            "aws",
            "dynamodb",
            "data-modeling",
            "database",
            "architecture",
            "skill"
          ],
          "homepage": "",
          "source": "./plugins/dynamodb-single-table",
          "installed": false
        },
        {
          "name": "nodejs-security",
          "description": "Writes secure Node.js applications by default, applying OWASP Top 10 mitigations, input validation, and safe authentication.",
          "version": "1.0.0",
          "author": "myskills",
          "category": "skill",
          "tags": [
            "nodejs",
            "security",
            "owasp",
            "authentication",
            "backend",
            "skill"
          ],
          "homepage": "",
          "source": "./plugins/nodejs-security",
          "installed": false
        },
        {
          "name": "csv-to-excel-report",
          "description": "Generates styled Excel reports from CSV data, merging transactions with targets and calculating KPIs into a formatted .xlsx workbook.",
          "version": "1.0.0",
          "author": "myskills",
          "category": "skill",
          "tags": [
            "excel",
            "csv",
            "reporting",
            "data",
            "openpyxl",
            "skill"
          ],
          "homepage": "",
          "source": "./plugins/csv-to-excel-report",
          "installed": false
        },
        {
          "name": "context-audit",
          "description": "Analyzes all Claude Code context sources for conflicts, overlapping skill triggers, and ambiguity.",
          "version": "1.0.0",
          "author": "myskills",
          "category": "skill",
          "tags": [
            "claude-code",
            "meta",
            "context",
            "tooling",
            "audit",
            "skill"
          ],
          "homepage": "",
          "source": "./plugins/context-audit",
          "installed": false
        },
        {
          "name": "pdlc",
          "description": "Orchestrates a three-phase product development lifecycle workflow (Product, Architecture, Build) with human decision gates on local HTML pages.",
          "version": "1.0.0",
          "author": "pdlc",
          "category": "skill",
          "tags": [
            "workflow",
            "orchestration",
            "product",
            "process",
            "automation",
            "skill"
          ],
          "homepage": "",
          "source": "./plugins/pdlc",
          "installed": false
        },
        {
          "name": "speckit-specify",
          "description": "Creates or updates a feature specification from a natural language feature description in a spec-kit project structure.",
          "version": "1.0.0",
          "author": "learnsdd",
          "category": "skill",
          "tags": [
            "spec-driven",
            "specification",
            "planning",
            "speckit",
            "workflow",
            "skill"
          ],
          "homepage": "",
          "source": "./plugins/speckit-specify",
          "installed": false
        },
        {
          "name": "explain-code-spanish",
          "description": "Explains code in both English and Spanish to support bilingual developer learning.",
          "version": "1.0.0",
          "author": "mindmap",
          "category": "skill",
          "tags": [
            "documentation",
            "education",
            "bilingual",
            "spanish",
            "explain",
            "skill"
          ],
          "homepage": "",
          "source": "./plugins/explain-code-spanish",
          "installed": false
        },
        {
          "name": "vote-overlay",
          "description": "Adds a feature-flagged section-voting overlay to React sites: per-section agree/disagree/unsure voting with comments, JSON ballot export, and a results mode tallying multiple ballot files inline and in a summary panel.",
          "version": "1.0.0",
          "author": "myskills",
          "category": "skill",
          "tags": [
            "frontend",
            "react",
            "feedback",
            "voting",
            "review",
            "skill"
          ],
          "homepage": "",
          "source": "./plugins/vote-overlay",
          "installed": false
        },
        {
          "name": "eval-methodology",
          "description": "Fair, reproducible skill evaluations across models and versions. Separates generation from grading, enforces complete coverage, and uses cost-aware tiebreaking.",
          "version": "1.0.0",
          "author": "myskills",
          "category": "skill",
          "tags": [
            "eval",
            "testing",
            "benchmarking",
            "multi-model",
            "methodology",
            "skill"
          ],
          "homepage": "",
          "source": "./plugins/eval-methodology",
          "installed": false
        },
        {
          "name": "eval-rebase",
          "description": "Eval versioning and consistency enforcement. Tracks eval lineage so every score is traceable to the exact criteria, skill version, and model that produced it.",
          "version": "1.0.0",
          "author": "myskills",
          "category": "skill",
          "tags": [
            "eval",
            "versioning",
            "lineage",
            "consistency",
            "methodology",
            "skill"
          ],
          "homepage": "",
          "source": "./plugins/eval-rebase",
          "installed": false
        },
        {
          "name": "dashboard-management",
          "description": "Auto-generated eval dashboard from JSONL results. Shows cross-model comparisons, version history, skill impact vs baseline, and cost-aware best-for-task rankings.",
          "version": "1.0.0",
          "author": "myskills",
          "category": "skill",
          "tags": [
            "dashboard",
            "eval",
            "reporting",
            "visualization",
            "methodology",
            "skill"
          ],
          "homepage": "",
          "source": "./plugins/dashboard-management",
          "installed": false
        }
      ],
      "generatedAt": "2026-07-19T12:08:09.355Z",
      "mode": "marketplace.json"
    }
  ]
};
